CREATE TABLE city
(
	id SERIAL,
	name VARCHAR(60) UNIQUE NOT NULL,
	description VARCHAR(255) NOT NULL,
	create_date TIMESTAMP NOT NULL,
	update_date TIMESTAMP NOT NULL,
	CONSTRAINT PK_city PRIMARY KEY (id)
);