INSERT INTO city(name, create_date, update_date) VALUES('Минск', current_date, current_date),
('Витебск', current_date, current_date),
('Гродно', current_date, current_date),
('Гомель', current_date, current_date),
('Брест', current_date, current_date),
('Могилев', current_date, current_date),
('Бобруйск', current_date, current_date),
('Москва', current_date, current_date),
('Пинск', current_date, current_date),
('Полоцк', current_date, current_date) ;
INSERT INTO city_info(info, city_id, create_date, update_date) VALUES('информация о Минске', 1, current_date, current_date),
('информация о Витебске', 2, current_date, current_date),
('информация о Гродно', 3, current_date, current_date),
('информация о Гомеле', 4, current_date, current_date),
('информация о Бресте', 5, current_date, current_date),
('информация о Могилёве', 6, current_date, current_date),
('информация о Бобруйске', 7, current_date, current_date),
('информация о Москве', 8, current_date, current_date),
('информация о пинске', 9, current_date, current_date),
('информация о Полоцке', 10, current_date, current_date);
