INSERT INTO city(name, description, create_date, update_date) VALUES('Минск', 'информация о Минске', current_date, current_date),
('Витебск', 'информация о Витебске', current_date, current_date),
('Гродно', 'информация о Гродно', current_date, current_date),
('Гомель', 'информация о Гомеле', current_date, current_date),
('Брест', 'информация о Бресте', current_date, current_date),
('Могилев', 'информация о Могилёве', current_date, current_date),
('Бобруйск', 'информация о Бобруйске', current_date, current_date),
('Москва', 'информация о Москве', current_date, current_date),
('Пинск', 'информация о Пинске', current_date, current_date),
('Полоцк', 'информация о Полоцке', current_date, current_date);
